@startuml
skinparam shadowing false
skinparam rectangle {
  roundCorner 10
}
skinparam defaultFontSize 12

left to right direction

rectangle "**Bundle: CH MTP Document**" as Bundle #orange/yellow {

  together {
    rectangle "**Entry: Composition**" as Comp #cornflowerblue/lightblue {
      rectangle "Patient – Mother (Reference)    " as SecMother #yellowgreen
      rectangle "Patient – Newborn                    " as SecNewborn #yellowgreen
      rectangle "RelatedPerson – Mother           " as SecRelated #yellowgreen
      rectangle "RelatedPerson – Partner           " as SecPartner #yellowgreen
      rectangle "Practitioner – Midwife               " as SecMidwife #yellowgreen
      rectangle "Condition – Pregnancy              " as SecCondition #yellowgreen
      rectangle "Observation – Pregnancy          " as SecObs #yellowgreen
      rectangle "Observation – Pregnancy Status" as SecStatus #yellowgreen
      rectangle "Encounter – Prenatal Visit          " as SecVisit #yellowgreen
      rectangle "Episode of Care                        " as SecEpisode #yellowgreen
    }
  }

  together {
    rectangle "[[StructureDefinition-ch-mtp-patient-mother.html Entry: Patient (Mother)]]" as E1 #salmon
    rectangle "[[StructureDefinition-ch-mtp-patient-newborn.html Entry: Patient (Newborn)]]" as E2 #salmon
    rectangle "[[StructureDefinition-ch-mtp-relatedperson-mother.html Entry: RelatedPerson (Mother)]]" as E3 #salmon
    rectangle "[[StructureDefinition-ch-mtp-relatedperson-partner.html Entry: RelatedPerson (Partner)]]" as E4 #salmon
    rectangle "[[StructureDefinition-ch-mtp-practitioner-midwife.html Entry: Practitioner (Midwife)]]" as E5 #salmon
    rectangle "[[StructureDefinition-ch-mtp-condition-pregnancy.html Entry: Condition (Pregnancy)]]" as E6 #salmon
    rectangle "[[StructureDefinition-ch-mtp-observation-pregnancy.html Entry: Observation (Pregnancy)]]" as E7 #salmon
    rectangle "[[StructureDefinition-ch-mtp-pregnancy-status.html Entry: Observation (Pregnancy Status)]]" as E8 #salmon
    rectangle "[[StructureDefinition-ch-mtp-prenatal-visit.html Entry: Encounter (Prenatal Visit)]]" as E9 #salmon
    rectangle "[[StructureDefinition-ch-mtp-episode-of-care.html Entry: EpisodeOfCare]]" as E10 #salmon
  }
}

SecMother   ..> E1
SecNewborn  ..> E2
SecRelated  ..> E3
SecPartner  ..> E4
SecMidwife  ..> E5
SecCondition ..> E6
SecObs      ..> E7
SecStatus   ..> E8
SecVisit    ..> E9
SecEpisode  ..> E10

@enduml
